import { useEffect, useMemo, useState } from 'react'
import { ExternalLink, RefreshCw } from 'lucide-react'
import type { Deal, GameEcosystem, Language } from '../shared/dealTypes'
import type { LibraryGame } from '../shared/libraryTypes'
import { getGameEcosystem } from '../shared/gameIdentity'
import { buildPurchasePlan, formatMoney, parseMoney, type ExclusionReason } from '../lib/planner'

export function PurchasePlan({ games, deals, country, language, ecosystem = 'pc', busy, onCheck }: { games: LibraryGame[]; deals: Deal[]; country: string; language: Language; ecosystem?: GameEcosystem; busy: boolean; onCheck: () => Promise<void> }) {
  const es = language === 'es'
  const [platform, setPlatform] = useState<GameEcosystem | 'all'>(ecosystem)
  const selectedGames = useMemo(() => games.filter((game) => platform === 'all' || getGameEcosystem(game) === platform), [games, platform])
  const currencies = [...new Set(['USD', ...(country === 'CO' ? ['COP'] : []), ...[...deals, ...selectedGames.flatMap((game) => game.snapshot ? [game.snapshot] : [])].filter((deal) => deal.countries.some((code) => code.toUpperCase() === country)).map((deal) => deal.salePrice.currency)])].sort()
  const defaultCop = country === 'CO' && ecosystem !== 'playstation'
  const [currency, setCurrency] = useState(defaultCop ? 'COP' : 'USD')
  const [budgetInput, setBudgetInput] = useState(defaultCop ? '100000' : '30')
  const [committed, setCommitted] = useState<{ budget: number; currency: string } | null>(null)
  const [inputError, setInputError] = useState(false)
  const [now, setNow] = useState(Date.now)
  useEffect(() => { const interval = window.setInterval(() => setNow(Date.now()), 30000); return () => window.clearInterval(interval) }, [])
  const plan = useMemo(() => committed ? buildPurchasePlan(selectedGames, deals, committed.budget, committed.currency, country, now) : null, [selectedGames, deals, committed, country, now])
  const reason = (value: ExclusionReason) => ({ owned: es ? 'Ya está en tu biblioteca' : 'Already owned', unwatched: es ? 'No lo estás vigilando' : 'Not watched', missing: es ? 'Sin oferta actual' : 'No current offer', stale: es ? 'Precio sin actualizar en 30 min' : 'Price older than 30 min', expired: es ? 'Oferta finalizada' : 'Expired offer', upcoming: es ? 'Oferta aún no activa' : 'Upcoming offer', country: es ? 'Región no compatible o desconocida' : 'Unsupported or unknown region', currency: es ? 'Sin precio en esta moneda' : 'No price in this currency', risk: es ? 'Destino o fuente sin verificar' : 'Unverified source or destination', budget: es ? 'No cabe en el presupuesto restante' : 'Does not fit remaining budget' })[value]
  return <section className="personal-section"><div className="personal-heading"><div><p className="personal-eyebrow">{es ? 'Tu próxima compra' : 'Your next purchase'}</p><h3>{es ? 'Haz que el presupuesto alcance' : 'Make your budget count'}</h3><p>{es ? 'Una selección de tus favoritos disponibles ahora.' : 'A selection of favorites available now.'}</p></div><button type="button" onClick={() => void onCheck()} disabled={busy}><RefreshCw size={16} />{es ? 'Actualizar precios' : 'Refresh prices'}</button></div>
    <form className="personal-form-row" onSubmit={(event) => { event.preventDefault(); const amount = parseMoney(budgetInput); setInputError(amount === undefined); if (amount !== undefined) setCommitted({ budget: amount, currency }) }}><label>{es ? 'Plataformas del plan' : 'Plan platforms'}<select value={platform} onChange={(event) => { setPlatform(event.target.value as GameEcosystem | 'all'); setCommitted(null) }}><option value="all">{es ? 'Todas mis plataformas' : 'All my platforms'}</option><option value="pc">PC</option><option value="playstation">PlayStation</option><option value="xbox">Xbox</option></select></label><label>{es ? 'Presupuesto' : 'Budget'}<input type="text" inputMode="decimal" autoComplete="off" value={budgetInput} onChange={(event) => setBudgetInput(event.target.value)} aria-invalid={inputError} aria-describedby={inputError ? 'plan-money-error' : undefined} required /></label><label>{es ? 'Moneda' : 'Currency'}<select value={currency} onChange={(event) => setCurrency(event.target.value)}>{currencies.map((code) => <option key={code}>{code}</option>)}</select></label><button type="submit" className="personal-primary">{es ? 'Calcular plan' : 'Build plan'}</button></form>
    {inputError ? <p id="plan-money-error" className="personal-error" role="alert">{es ? 'Introduce un importe positivo o cero, sin separadores de miles, con hasta 2 decimales.' : 'Enter zero or a positive amount, no grouping separators, up to 2 decimal places.'}</p> : null}
    <p className="personal-fine-print">{es ? 'Método: prioridad alta primero; a igual prioridad, menor precio. Añade cada juego si cabe en el saldo restante. Es una selección aproximada, no garantiza la combinación óptima. No reserva precios ni compra por ti.' : 'Method: highest priority first, then lowest price. Each game is added if it fits the remaining budget. This approximation does not guarantee the optimal combination. It neither reserves prices nor purchases games.'}</p>
    {plan && committed ? <div aria-live="polite"><div className="personal-facts"><div><span>{es ? 'Juegos' : 'Games'}</span><strong>{plan.items.length}</strong></div><div><span>{es ? 'Total estimado' : 'Estimated total'}</span><strong>{formatMoney(plan.total, committed.currency, language)}</strong></div><div><span>{es ? 'Te queda' : 'Remaining'}</span><strong>{formatMoney(plan.remaining, committed.currency, language)}</strong></div></div>
      {plan.items.length ? <ol className="plan-list">{plan.items.map(({ game, deal, amount }) => <li key={game.id}><div><strong>{game.title}</strong><small>{deal.platform} · {deal.source} · {es ? 'Prioridad' : 'Priority'} {game.priority}</small></div><strong>{formatMoney(amount, committed.currency, language)}</strong><a className="personal-button" href={deal.url} target="_blank" rel="noreferrer" aria-label={`${es ? 'Ver oferta de' : 'View offer for'} ${game.title}`}><ExternalLink size={16} /></a></li>)}</ol> : <div className="personal-empty"><h4>{es ? 'No hay compras que cumplan tus condiciones' : 'No purchases match these conditions'}</h4><p>{es ? 'Añade favoritos, actualiza los precios o ajusta el presupuesto y la moneda.' : 'Add favorites, refresh prices or adjust the budget and currency.'}</p></div>}
      {plan.excluded.length ? <details className="personal-data-table"><summary>{es ? 'Juegos no incluidos y motivos' : 'Excluded games and reasons'} ({plan.excluded.length})</summary><ul className="personal-evidence">{plan.excluded.map(({ game, reason: why }) => <li key={game.id}><strong>{game.title}</strong> — {reason(why)}</li>)}</ul></details> : null}
    </div> : <div className="personal-empty"><p>{es ? 'Elige tu presupuesto para ver una propuesta y las razones de cada exclusión.' : 'Choose a budget to see a proposal and the reason for each exclusion.'}</p></div>}
    <p className="personal-fine-print">{es ? 'Solo usa precios con menos de 30 minutos, activos, de bajo riesgo y con enlace directo. Excluye poseídos en esa misma plataforma y regiones distintas. No reemplaza licencias de consola por ofertas de PC. USD puede ser una conversión aproximada; otras monedas requieren precio nativo. Impuestos, comisiones y elegibilidad de la cuenta deben verificarse en la tienda.' : 'Uses active, low-risk prices less than 30 minutes old with direct links. Excludes games owned on the same platform and other regions. It does not replace console licenses with PC offers. USD may be approximate; other currencies require native prices. Verify taxes, fees and account eligibility at checkout.'}</p>
  </section>
}
